---
title: "dodatna_tocka"
author: "Porez123"
date: "2025-01-25"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
```

Podatci

```{r}
data <- read.csv("../data/data.csv")
head(data)

```

```{r}
stripped <- select(data, c("previous_contacts_count", "previous_campaign_outcome"))
tail(stripped)
```
```{r}
unique(stripped$previous_campaign_outcome)

for (col_name in names(stripped)){
  if (sum(is.na(stripped[,col_name])) > 0){
    cat('Ukupno nedostajućih vrijednosti za varijablu ',col_name, ': ', sum(is.na(stripped[,col_name])),'\n')
  }
}

cat('\nDimenzije podataka: ',dim(stripped))
```

```{r}
final <- subset(stripped, previous_campaign_outcome != "unknown")
head(final)
summary(final)
final <- subset(final, previous_contacts_count <=50)
summary(final)
hist(final$previous_contacts_count, 
     breaks = seq(min(final$previous_contacts_count), max(final$previous_contacts_count), by = 1), 
     main = "Histogram of Previous Contacts Count", 
     xlab = "Previous Contacts Count", 
     col = "skyblue", 
     border = "black")

```
```{r}
prev_success  = final[final$previous_campaign_outcome=="success",]
prev_failure  = final[final$previous_campaign_outcome=="failure",]
prev_other  = final[final$previous_campaign_outcome=="other",]
cat( mean(prev_success$previous_contacts_count),'\n')
cat( mean(prev_failure$previous_contacts_count),'\n')
cat( mean(prev_other$previous_contacts_count),'\n')
boxplot(prev_success$previous_contacts_count, prev_failure$previous_contacts_count, prev_other$previous_contacts_count,  
        names = c('success','failure', 'other'),
        main='Usporedba razine uspijeha')
```

```{r}
library(nortest)
hist(prev_success$previous_contacts_count, 
     main='Histogram primary',
     xlab='Duljina poziva')
hist(prev_failure$previous_contacts_count, 
     main='Histogram secondary',
     xlab='Duljina poziva')
hist(prev_other$previous_contacts_count, 
     main='Histogram tertiary',
     xlab='Duljina poziva')


qqnorm(prev_success$previous_contacts_count, pch = 1, frame = FALSE,main='primary')
qqline(prev_success$previous_contacts_count, col = "steelblue", lwd = 2)

qqnorm(prev_failure$previous_contacts_count, pch = 1, frame = FALSE,main='secondary')
qqline(prev_failure$previous_contacts_count, col = "steelblue", lwd = 2)

qqnorm(prev_other$previous_contacts_count, pch = 1, frame = FALSE,main='tertiary')
qqline(prev_other$previous_contacts_count, col = "steelblue", lwd = 2)

#ks.test(primary$last_contact_duration, "pnorm", mean = mean(primary$last_contact_duration), sd = sd(primary$last_contact_duration))
#ks.test(secondary$last_contact_duration, "pnorm", mean = mean(secondary$last_contact_duration), sd = sd(secondary$last_contact_duration))
#ks.test(tertiary$last_contact_duration, "pnorm", mean = mean(tertiary$last_contact_duration), sd = sd(tertiary$last_contact_duration))
lillie.test(prev_success$previous_contacts_count)
lillie.test(prev_failure$previous_contacts_count)
lillie.test(prev_other$previous_contacts_count)

```
Podatci nisu normalni nego ludi i zbunjeni.

Testiramo homogenost varijance.

```{r}
fligner.test(list(prev_success$previous_contacts_count, prev_failure$previous_contacts_count, prev_other$previous_contacts_count))
```
Nisu homogene varijnce.

```{r}
data <- data.frame(
  value = c(prev_success$previous_contacts_count, prev_failure$previous_contacts_count, prev_other$previous_contacts_count),
  group = rep(c("primary", "secondary", "tertiary"), times = c(length(prev_success$previous_contacts_count), length(prev_failure$previous_contacts_count), length(prev_other$previous_contacts_count)))  # Group labels
)

# Perform the Kruskal-Wallis test
kruskal_result <- kruskal.test(value ~ group, data = data)

# View the result of the test
print(kruskal_result)
```

```{r}

wilcox.test(prev_failure$previous_contacts_count, prev_other$previous_contacts_count)
wilcox.test(prev_success$previous_contacts_count, prev_other$previous_contacts_count)
wilcox.test(prev_success$previous_contacts_count,prev_failure$previous_contacts_count)
```